[package]
name = "asciigen"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
fast_image_resize = "4.2"
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
rusttype = "0.9"
rayon = "1.10"

[dev-dependencies]
mockall = "0.13"